name: rigid
channels:
  - conda-forge
  - defaults
dependencies:
  - scipy
  - numpy
  - pyamg
  - pybind11
  - StochasticHydroTools::libMobility
  - matplotlib
  - numba
  - cxx-compiler
  - eigen
  - pytest
